services:
  - type: web
    name: tm-asociados-gestion-juridica
    runtime: static
    staticPublishPath: .
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
